"""remove unique from filename

Revision ID: 447496fa9851
Revises: 714d6a4b861f
Create Date: 2021-06-18 14:26:29.220073

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "447496fa9851"
down_revision = "714d6a4b861f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_output_file_filename", table_name="output_file")
    op.create_index(
        op.f("ix_output_file_filename"), "output_file", ["filename"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_output_file_filename"), table_name="output_file")
    op.create_index(
        "ix_output_file_filename", "output_file", ["filename"], unique=False
    )
    # ### end Alembic commands ###
