"""add request reference to user and args to request

Revision ID: 5340b1e2ef60
Revises: 974415834c6e
Create Date: 2021-06-18 09:41:47.663981

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5340b1e2ef60"
down_revision = "974415834c6e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "request",
        sa.Column("args", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    )
    op.alter_column("request", "user_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_constraint("request_user_id_fkey", "request", type_="foreignkey")
    op.create_foreign_key(None, "request", "user", ["user_id"], ["id"])
    op.add_column("user", sa.Column("disk_quota", sa.BigInteger(), nullable=True))
    op.drop_column("user", "my_custom_field")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "my_custom_field",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("user", "disk_quota")
    op.drop_constraint(None, "request", type_="foreignkey")
    op.create_foreign_key(
        "request_user_id_fkey", "request", "request", ["user_id"], ["id"]
    )
    op.alter_column("request", "user_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_column("request", "args")
    # ### end Alembic commands ###
