"""empty message

Revision ID: 6041a4915c53
Revises: 5597f4b675f4
Create Date: 2023-01-19 09:19:11.395199

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6041a4915c53"
down_revision = "5597f4b675f4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("output_file", schema=None) as batch_op:
        batch_op.alter_column(
            "filename",
            existing_type=sa.VARCHAR(length=128),
            type_=sa.Text(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("output_file", schema=None) as batch_op:
        batch_op.alter_column(
            "filename",
            existing_type=sa.Text(),
            type_=sa.VARCHAR(length=128),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
