"""add timestamp in output_file

Revision ID: 714d6a4b861f
Revises: b6fb5d00d6c0
Create Date: 2021-06-18 13:48:58.579660

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "714d6a4b861f"
down_revision = "b6fb5d00d6c0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "output_file", sa.Column("timestamp", sa.String(length=64), nullable=False)
    )
    op.alter_column(
        "output_file", "filename", existing_type=sa.VARCHAR(length=64), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "output_file", "filename", existing_type=sa.VARCHAR(length=64), nullable=True
    )
    op.drop_column("output_file", "timestamp")
    # ### end Alembic commands ###
