"""add request and output_file

Revision ID: 974415834c6e
Revises: c0df6c6f1d2d
Create Date: 2021-05-24 22:35:13.761016

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "974415834c6e"
down_revision = "c0df6c6f1d2d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "request",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("submission_date", sa.DateTime(), nullable=True),
        sa.Column("end_date", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("task_id", sa.String(length=64), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["request.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_request_name"), "request", ["name"], unique=False)
    op.create_index(op.f("ix_request_task_id"), "request", ["task_id"], unique=True)
    op.create_table(
        "output_file",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=64), nullable=True),
        sa.Column("size", sa.BigInteger(), nullable=True),
        sa.Column("request_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["request.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_output_file_filename"), "output_file", ["filename"], unique=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_output_file_filename"), table_name="output_file")
    op.drop_table("output_file")
    op.drop_index(op.f("ix_request_task_id"), table_name="request")
    op.drop_index(op.f("ix_request_name"), table_name="request")
    op.drop_table("request")
    # ### end Alembic commands ###
