"""empty message

Revision ID: ce8080af44a6
Revises: 447496fa9851
Create Date: 2021-10-19 13:07:33.845340

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ce8080af44a6"
down_revision = "447496fa9851"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "output_file", "timestamp", existing_type=sa.VARCHAR(length=64), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "output_file", "timestamp", existing_type=sa.VARCHAR(length=64), nullable=False
    )
    # ### end Alembic commands ###
