version: "3.8"
services:
  backend:
    build: ${PROJECT_DIR}/builds/backend
    image: hl-dds/backend:${RAPYDO_VERSION}
    volumes:
      - ${DATA_DIR}/catalog:/catalog
    environment:
      BROKER_ENABLE: ${ACTIVATE_BROKER}
      BROKER_ENABLE_CONNECTOR: ${BROKER_ENABLE_CONNECTOR}
      BROKER_HOST: ${BROKER_HOST}
      BROKER_PORT: ${BROKER_PORT}
      BROKER_CATALOG_DIR: ${BROKER_CATALOG_DIR}
  celery:
    build: ${PROJECT_DIR}/builds/backend
    image: hl-dds/backend:${RAPYDO_VERSION}
    volumes:
      - ${DATA_DIR}/catalog:/catalog
    environment:
      BROKER_ENABLE: ${ACTIVATE_BROKER}
      BROKER_ENABLE_CONNECTOR: ${BROKER_ENABLE_CONNECTOR}
      BROKER_HOST: ${BROKER_HOST}
      BROKER_PORT: ${BROKER_PORT}
      BROKER_CATALOG_DIR: ${BROKER_CATALOG_DIR}
