# Customize this file to include compose configurations common to bluprints
version: "3.2"
services:
  backend:
    build: ${PROJECT_DIR}/builds/backend
    image: hl-dds/backend:${RAPYDO_VERSION}
    volumes:
      - ${VANILLA_DIR}/data/catalog:/catalog
    environment:
      BROKER_ENABLE: ${ACTIVATE_BROKER}
      BROKER_ENABLE_CONNECTOR: ${BROKER_ENABLE_CONNECTOR}
      BROKER_HOST: ${BROKER_HOST}
      BROKER_PORT: ${BROKER_PORT}
      BROKER_CATALOG_DIR: ${BROKER_CATALOG_DIR}
  celery:
    build: ${PROJECT_DIR}/builds/backend
    image: hl-dds/backend:${RAPYDO_VERSION}
    volumes:
      - ${VANILLA_DIR}/data/catalog:/catalog
    environment:
      BROKER_ENABLE: ${ACTIVATE_BROKER}
      BROKER_ENABLE_CONNECTOR: ${BROKER_ENABLE_CONNECTOR}
      BROKER_HOST: ${BROKER_HOST}
      BROKER_PORT: ${BROKER_PORT}
      BROKER_CATALOG_DIR: ${BROKER_CATALOG_DIR}
  geoserver:
    #    image: geonode/geoserver:2.19.1
    build: ${PROJECT_DIR}/builds/geoserver
    image: hl-geoserver:${PROJECT_VERSION}
    environment:
      ACTIVATE: ${ACTIVATE_GEOSERVER}
    volumes:
      - ${VANILLA_DIR}/data/geoserver:/geoserver_data/data
    networks:
      app_net:
        aliases:
          - geoserver.dockerized.io
