version: "3.9"
services:
  backend:
    build: ${PROJECT_DIR}/builds/backend
    image: hl-dds/backend:${RAPYDO_VERSION}
    volumes:
      - ${DATA_DIR}/catalog:/catalog
    environment:
      BROKER_ENABLE: ${ACTIVATE_BROKER}
      BROKER_ENABLE_CONNECTOR: ${BROKER_ENABLE_CONNECTOR}
      BROKER_HOST: ${BROKER_HOST}
      BROKER_PORT: ${BROKER_PORT}
      BROKER_CATALOG_DIR: ${BROKER_CATALOG_DIR}
      CARTOPY_DATA_DIR: ${CARTOPY_DATA_DIR}
  celery:
    build: ${PROJECT_DIR}/builds/backend
    image: hl-dds/backend:${RAPYDO_VERSION}
    volumes:
      - ${DATA_DIR}/catalog:/catalog
    environment:
      BROKER_ENABLE: ${ACTIVATE_BROKER}
      BROKER_ENABLE_CONNECTOR: ${BROKER_ENABLE_CONNECTOR}
      BROKER_HOST: ${BROKER_HOST}
      BROKER_PORT: ${BROKER_PORT}
      BROKER_CATALOG_DIR: ${BROKER_CATALOG_DIR}
      DATASETS_PATH: ${DATASETS_PATH}
      CACHE_PATH: ${CACHE_PATH}
  celerybeat:
    build: ${PROJECT_DIR}/builds/backend
    image: hl-dds/backend:${RAPYDO_VERSION}
  flower:
    build: ${PROJECT_DIR}/builds/backend
    image: hl-dds/backend:${RAPYDO_VERSION}
  geoserver:
    image: hl-geoserver:${PROJECT_VERSION}
    build:
      context: ${SUBMODULE_DIR}/geoserver
      args:
        GEOSERVER_UID: ${CURRENT_UID}
        GEOSERVER_GID: ${CURRENT_GID}
        IMAGE_VERSION: 9.0-jdk11-openjdk-slim-buster
    environment:
      ACTIVATE: ${ACTIVATE_GEOSERVER}
      STABLE_EXTENSIONS: netcdf-plugin
      TOMCAT_EXTRAS: false
      EXISTING_DATA_DIR: ${GEOSERVER_EXISTING_DATA_DIR}
      GEOSERVER_ADMIN_USER: ${GEOSERVER_ADMIN_USER}
      GEOSERVER_ADMIN_PASSWORD: ${GEOSERVER_ADMIN_PASSWORD}
      RECREATE_DATADIR: ${GEOSERVER_RECREATE_DATADIR}
    volumes:
      - ${DATA_DIR}/geoserver/data_dir:/opt/geoserver/data_dir
      - ${DATA_DIR}/geoserver/settings:/settings
    networks:
      default:
        aliases:
          - geoserver.dockerized.io
  frontend:
    environment:
      INJECT_MAPS_URL: ${MAPS_URL}
