# Customize this file to include compose configurations common to bluprints
version: "3.2"
services:
  backend:
    build: ${VANILLA_DIR}/projects/${COMPOSE_PROJECT_NAME}/builds/backend
    image: hl-dds/backend:${RAPYDO_VERSION}
    volumes:
      - ${VANILLA_DIR}/data/catalog:/catalog
  celery:
    build: ${VANILLA_DIR}/projects/${COMPOSE_PROJECT_NAME}/builds/backend
    image: hl-dds/backend:${RAPYDO_VERSION}
    volumes:
      - ${VANILLA_DIR}/data/catalog:/catalog
