# Customize this file to include compose configurations common to bluprints
version: "3.2"
services:
  backend:
    build: ${VANILLA_DIR}/projects/${COMPOSE_PROJECT_NAME}/builds/backend
    image: hl-dds/backend:${RAPYDO_VERSION}
    volumes:
      - ${VANILLA_DIR}/data/catalog:/catalog
    environment:
      BROKER_ENABLE: ${ACTIVATE_BROKER}
      BROKER_ENABLE_CONNECTOR: ${BROKER_ENABLE_CONNECTOR}
      BROKER_HOST: ${BROKER_HOST}
      BROKER_PORT: ${BROKER_PORT}
      BROKER_CATALOG_DIR: ${BROKER_CATALOG_DIR}
  celery:
    build: ${VANILLA_DIR}/projects/${COMPOSE_PROJECT_NAME}/builds/backend
    image: hl-dds/backend:${RAPYDO_VERSION}
    volumes:
      - ${VANILLA_DIR}/data/catalog:/catalog
    environment:
      BROKER_ENABLE: ${ACTIVATE_BROKER}
      BROKER_ENABLE_CONNECTOR: ${BROKER_ENABLE_CONNECTOR}
      BROKER_HOST: ${BROKER_HOST}
      BROKER_PORT: ${BROKER_PORT}
      BROKER_CATALOG_DIR: ${BROKER_CATALOG_DIR}
  geoserver:
    image: geonode/geoserver:2.18.2
    ports:
      - 8070:8080
    environment:
      ACTIVATE: ${ACTIVATE_GEOSERVER}
    volumes:
      - ${VANILLA_DIR}/data/geoserver:/geoserver_data/data
