version: "3.9"
services:
  backend:
    build: ${PROJECT_DIR}/builds/backend
    image: hl-dds/backend:${RAPYDO_VERSION}
    volumes:
      - ${DATA_DIR}/catalog:/catalog
    environment:
      BROKER_ENABLE: ${ACTIVATE_BROKER}
      BROKER_ENABLE_CONNECTOR: ${BROKER_ENABLE_CONNECTOR}
      BROKER_HOST: ${BROKER_HOST}
      BROKER_PORT: ${BROKER_PORT}
      BROKER_CATALOG_DIR: ${BROKER_CATALOG_DIR}
  celery:
    build: ${PROJECT_DIR}/builds/backend
    image: hl-dds/backend:${RAPYDO_VERSION}
    volumes:
      - ${DATA_DIR}/catalog:/catalog
    environment:
      BROKER_ENABLE: ${ACTIVATE_BROKER}
      BROKER_ENABLE_CONNECTOR: ${BROKER_ENABLE_CONNECTOR}
      BROKER_HOST: ${BROKER_HOST}
      BROKER_PORT: ${BROKER_PORT}
      BROKER_CATALOG_DIR: ${BROKER_CATALOG_DIR}
      DATASETS_PATH: ${DATASETS_PATH}
  celerybeat:
    build: ${PROJECT_DIR}/builds/backend
    image: hl-dds/backend:${RAPYDO_VERSION}
  flower:
    build: ${PROJECT_DIR}/builds/backend
    image: hl-dds/backend:${RAPYDO_VERSION}
  geoserver:
    #    image: geonode/geoserver:2.19.1
    build:
      context: ${PROJECT_DIR}/builds/geoserver
      args:
        CURRENT_UID: ${CURRENT_UID}
        CURRENT_GID: ${CURRENT_GID}
    image: hl-geoserver:${PROJECT_VERSION}
    environment:
      ACTIVATE: ${ACTIVATE_GEOSERVER}
    volumes:
      - ${DATA_DIR}/geoserver:/geoserver_data/data
    networks:
      default:
        aliases:
          - geoserver.dockerized.io
