version: "3.9"
services:
  backend:
    build: ${PROJECT_DIR}/builds/backend
    image: hl-dds/backend:${RAPYDO_VERSION}
    volumes:
      - ${DATA_DIR}/catalog:/catalog
    environment:
      BROKER_ENABLE: ${ACTIVATE_BROKER}
      BROKER_ENABLE_CONNECTOR: ${BROKER_ENABLE_CONNECTOR}
      BROKER_HOST: ${BROKER_HOST}
      BROKER_PORT: ${BROKER_PORT}
      BROKER_CATALOG_DIR: ${BROKER_CATALOG_DIR}
  celery:
    build: ${PROJECT_DIR}/builds/backend
    image: hl-dds/backend:${RAPYDO_VERSION}
    volumes:
      - ${DATA_DIR}/catalog:/catalog
    environment:
      BROKER_ENABLE: ${ACTIVATE_BROKER}
      BROKER_ENABLE_CONNECTOR: ${BROKER_ENABLE_CONNECTOR}
      BROKER_HOST: ${BROKER_HOST}
      BROKER_PORT: ${BROKER_PORT}
      BROKER_CATALOG_DIR: ${BROKER_CATALOG_DIR}
      DATASETS_PATH: ${DATASETS_PATH}
  celerybeat:
    build: ${PROJECT_DIR}/builds/backend
    image: hl-dds/backend:${RAPYDO_VERSION}
  flower:
    build: ${PROJECT_DIR}/builds/backend
    image: hl-dds/backend:${RAPYDO_VERSION}
  geoserver:
    image: hl-geoserver:${PROJECT_VERSION}
    build:
      context: ${SUBMODULE_DIR}/geoserver
      args:
        GEOSERVER_UID: ${CURRENT_UID}
        GEOSERVER_GID: ${CURRENT_GID}
        IMAGE_VERSION: 9.0-jdk11-openjdk-slim-buster
    environment:
      ACTIVATE: ${ACTIVATE_GEOSERVER}
      STABLE_EXTENSIONS: netcdf-plugin
      TOMCAT_EXTRAS: false
    volumes:
      - ${DATA_DIR}/geoserver:/opt/geoserver/data_dir
      - ${DATA_DIR}/catalog/datasets:/opt/geoserver/data_dir/datasets
    networks:
      default:
        aliases:
          - geoserver.dockerized.io
