version: "3.9"

services:
  backend:
    volumes:
      - /data:/catalog/datasets
  celery:
    volumes:
      - /data:/catalog/datasets
  geoserver:
    volumes:
      - /data/datasets:/opt/geoserver/data_dir/datasets
  proxy:
    volumes:
      - ${PROJECT_DIR}/confs/geoserver.service:/etc/nginx/sites-enabled/geoserver.service
