version: "3.9"

services:
  backend:
    volumes:
      - /data/datasets/vhr-rea:/catalog/datasets/era5-downscaled
      - /data/ECMWF/Sub_SEA/Italy:/catalog/datasets/sub-sea
      - /data/datasets/human-wellbeing:/catalog/datasets/human-wellbeing
  celery:
    volumes:
      - /data/datasets/vhr-rea:/catalog/datasets/era5-downscaled
      - /data/ECMWF/Sub_SEA/Italy:/catalog/datasets/sub-sea
      - /data/datasets/human-wellbeing:/catalog/datasets/human-wellbeing
  proxy:
    volumes:
      - ${PROJECT_DIR}/confs/geoserver.service:/etc/nginx/sites-enabled/geoserver.service
