name: Cypress

on:
  push:
  workflow_dispatch:
env:
  PROJECT: highlander

jobs:
  integration-tests:
    runs-on: ubuntu-20.04
    timeout-minutes: 45

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - uses: rapydo/actions/install@v1
        with:
          project: ${PROJECT}
          codecov_token: ${{ secrets.CODECOV_TOKEN }}

      - uses: rapydo/actions/setup-cypress@v1
        with:
          id: ${{ secrets.CYPRESS_PROJECT_ID }}
          key: ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: Run Cypress
        run: |

          # Temporary fix, waiting for a public release
          cd projects/highlander/builds/backend
          # git clone url path does not work
          git clone --depth https://${{ secrets.DDS_USER }}:${{ secrets.DDS_TOKEN }}@${{ secrets.DDS_URL }}/${{ secrets.DDS_USER }}/dds_backend
          mv dds_backend packages
          cd -

          rapydo pull --quiet;
          rapydo build

          rapydo -e API_AUTOSTART=1 start;
          sleep 20
          rapydo logs

          rapydo shell --no-tty frontend "yarn install"
          rapydo shell --no-tty frontend "reload-types"

          rapydo shell --no-tty frontend "yarn run cypress:start:full"

          rapydo shell --no-tty frontend "npx nyc --all report --reporter=lcov --report-dir /coverage"
          cp data/${PROJECT}/karma/lcov.info .
          bash <(curl -s https://codecov.io/bash)

      - name: Docker Logs
        if: failure()
        run: |
          rapydo logs
