name: Frontend

on:
  push:
  workflow_dispatch:
env:
  PROJECT: highlander

jobs:
  Development-mode:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - uses: rapydo/actions/install@v1
        with:
          project: ${PROJECT}

      - name: Run Karma
        run: |
          rapydo pull --quiet frontend
          rapydo start frontend
          sleep 5
          rapydo logs frontend
          rapydo shell frontend "yarn install"
          rapydo shell frontend "reload-types"
          rapydo shell frontend "yarn run test:single"

      - name: Coverage
        uses: rapydo/actions/coverage@v1
        with:
          repository: projects/${PROJECT}
          project: ${PROJECT}
          step: frontend

  Production-mode:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - uses: rapydo/actions/install@v1
        with:
          project: ${PROJECT}

      - name: Production mode
        run: |

          rapydo --testing --prod init --force
          rapydo pull --quiet frontend proxy

          rm projects/highlander/confs/geoserver.service
          touch projects/highlander/confs/geoserver.service

          rapydo start frontend proxy
          rapydo logs --follow frontend
          rapydo logs --tail 6 frontend | grep "files have been compressed."
          rapydo logs --tail 20 proxy
          curl --insecure -X GET https://localhost
