name: Frontend

on:
  push:
  workflow_dispatch:
env:
  PROJECT: highlander

jobs:
  frontend-tests:
    runs-on: ubuntu-20.04
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - uses: rapydo/actions/install@v1
        with:
          project: ${PROJECT}
          codecov_token: ${{ secrets.CODECOV_TOKEN }}

      - name: Run Karma
        run: |
          rapydo -s frontend pull --quiet
          rapydo -s frontend start
          sleep 5
          rapydo -s frontend logs
          rapydo shell --no-tty frontend "yarn install"
          rapydo shell --no-tty frontend "reload-types"
          rapydo shell --no-tty frontend "yarn run test:single"
          cp data/${PROJECT}/karma/lcov.info .
          bash <(curl -s https://codecov.io/bash)

      - name: Production mode
        run: |

          sudo mkdir /data/sub-sea
          sudo mkdir /data/vhr-rea

          rapydo remove --all
          rapydo --prod init --force
          rapydo -s frontend,proxy pull --quiet

          rm projects/highlander/confs/geoserver.service
          touch projects/highlander/confs/geoserver.service

          rapydo -s frontend,proxy start
          rapydo dump
          rapydo -s frontend logs --follow
          docker-compose logs --tail 6 frontend 2>&1 | grep "files have been compressed."
          docker-compose logs --tail 20 proxy
          curl --insecure -X GET https://localhost
