name: MyPy

env:
  PROJECT: highlander

on:
  push:
  workflow_dispatch:

jobs:
  mypy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: rapydo/actions/install@v2
        with:
          project: ${PROJECT}
          submodule: http-api
      - uses: rapydo/actions/mypy@v2
        with:
          project: ${PROJECT}
          install: numpy
          ignore: dds_backend
      - name: Save Report
        uses: actions/upload-artifact@v3
        with:
          name: mypy-report
          path: report
