---
project:
  title: Highlander
  description: "Data Delivery System"
  version: "0.5"
  rapydo: "2.3"

variables:
  # roles:
  #   normal_user: YourCustomName
  #   staff_user: YourCustomName
  #   # staff_user: disabled
  #   group_coordinator: YourCustomName
  #   admin_root: YourCustomName
  #   extra_role: YourExtraRole

  submodules:
    geoserver:
      online_url: https://github.com/giuseppetrotta/docker-geoserver
      branch: 2.21.0

  env:
    FRONTEND_FRAMEWORK: angular
    ENABLE_ANGULAR_SSR: 0
    AUTH_SERVICE: sqlalchemy

    ACTIVATE_ALCHEMY: 1
    ACTIVATE_POSTGRES: 1
    ACTIVATE_REDIS: 1
    ACTIVATE_CELERY: 1
    # ACTIVATE_FLOWER: 1
    ACTIVATE_CELERYBEAT: 1
    ACTIVATE_BROKER: 1
    ACTIVATE_GEOSERVER: 1

    CELERY_ENABLE_CONNECTOR: 1
    CELERY_POOL_MODE: solo
    BROKER_ENABLE_CONNECTOR: 1
    BROKER_HOST: nohost
    BROKER_PORT: 0
    BROKER_CATALOG_DIR: "/catalog"

    GEOSERVER_EXISTING_DATA_DIR: true
    GEOSERVER_ADMIN_USER: admin
    GEOSERVER_ADMIN_PASSWORD: D3vMode!
    GEOSERVER_RECREATE_DATADIR: false

    SET_CSP_IMG_SRC: "https://a.tile.openstreetmap.org https://b.tile.openstreetmap.org https://c.tile.openstreetmap.org"
    SET_CSP_FONT_SRC: https://netdna.bootstrapcdn.com

    RUN_SCHEMATHESIS: 0
    DATA_PATH: "/catalog/download"
    DATASETS_PATH: "/catalog/datasets"
    CACHE_PATH: "/catalog/cache"
    CARTOPY_DATA_DIR: "/cartopy"
    MAPS_URL: "**PLACEHOLDER**"
